# Generated by Django 4.2.7 on 2023-12-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0002_alter_issue_all_vote_count'),
        ('user_ddk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userddk',
            name='issue_id',
        ),
        migrations.AddField(
            model_name='userddk',
            name='issues',
            field=models.ManyToManyField(related_name='user_ddk_issues', to='issue.issue'),
        ),
    ]
