# Generated by Django 4.2.7 on 2023-12-16 08:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('content', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('issue_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('all_vote_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_content_1', to='content.content')),
                ('content_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_content_2', to='content.content')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
