# Generated by Django 4.2.7 on 2023-12-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
